# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/73cd2eed94c576213c5f25ab57adf6d8c83e792a/schema.json
schema_version: 1

context:
  name: bitwarden-cli
  version: cli-v2025.2.0
  python_min: 3.7.0

package:
  name: bitwarden-cli
  version: ${{ version }}

source:
  url: https://github.com/bitwarden/clients/archive/refs/tags/${{ version }}.tar.gz
  sha256: 83360ff8bc97980e4ff25c964c7bd3923d333d177aa4f7fb736b019f26c7cb41

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ==${{ python_min }}
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - bw
      pip_check: true

about:
  homepage: http://www.python.org/dev/peps/pep-3156/
  summary: reference implementation of PEP 3156
  license: Apache-2.0
  license_file: COPYING

extra:
  recipe-maintainers:
    - phreed
