# https://github.com/prefix-dev/rattler-build-action
name: Build Packages

on: [push]

jobs:
  build_packages:
    name: Build packages
    strategy:
      matrix:
        package: 
          # - asyncio
          # - bash-preexe
          # - bitwarden-cli
          - digitalpy
          # - dysk
          # - fd
          # - freetakserver
          # - fsarchiver
          # - iamb
          # - jank
          # - mediamtx
          # - metashell
          # - mumble
          # - node-red
          # - node-red-contrib-web-worldmap
          # - pwgen
          # - testresources
        target:
          - platform: linux-64
            os: "ubuntu-latest"
          # - platform: linux-aarch64
          #   os: "ubuntu-latest"
          # - platform: win-64
          #   os: "windows-latest"
          # - platform: osx-64
          #   os: "macos-latest"
          # - platform: osx-arm64
          #   os: "macos-14"
    runs-on: ${{ matrix.target.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Build conda package ${{ matrix.package }}
      uses: prefix-dev/rattler-build-action@v0.2.31
      with:
        recipe-path: ./packages/${{ matrix.package }}
        artifact-name: package-${{ matrix.target.platform }}
        build-args: --target-platform ${{ matrix.target.platform }}${{ matrix.target.platform == 'linux-aarch64' && ' --no-test' || '' }}
    - run: |
        # https://rattler.build/latest/authentication_and_upload/#anacondaorg
        for pkg in $(find output -type f \( -name "*.conda" -o -name "*.tar.bz2" \) ); do
          echo "Uploading ${pkg}"
          rattler-build upload anaconda -o phread -c dev "${pkg}"
        done
      env:
        ANACONDA_SERVER_URL: https://anaconda.org
        ANACONDA_USERNAME: phread
        ANACONDA_CHANNEL: mesomorph
        ANACONDA_API_KEY: ${{ secrets.ANACONDA_API_TOKEN }}

