# https://github.com/prefix-dev/rattler-build-action
name: Build Packages

on: [push]

jobs:
  build_packages:
    name: Build packages
    strategy:
      fail-fast: false
      matrix:
        package: 
          # - asyncio # is this included with python?
          - self: bash-preexec
          - self: bitwarden-cli
          - self: digitalpy
          - self: dysk
          - self: fd
          - self: freetakserver
            needs: [digitalpy]
          - self: fsarchiver
          - self: iamb
          - self: jank
          - self: mediamtx
          - self: metashell
          - self: mumble
          - self: node-red
          - self: node-red-contrib-web-worldmap
          - self: pwgen
          - self: testresources
        target:
          - platform: linux-64
            os: "ubuntu-latest"
          # - platform: linux-aarch64
          #   os: "ubuntu-latest"
          # - platform: win-64
          #   os: "windows-latest"
          # - platform: osx-64
          #   os: "macos-latest"
          # - platform: osx-arm64
          #   os: "macos-14"
    runs-on: ${{ matrix.target.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Build conda package ${{ matrix.package.self }}
      uses: prefix-dev/rattler-build-action@v0.2.32
      with:
        recipe-path: ./packages/${{ matrix.package.self }}
        artifact-name: ${{ matrix.package.self }}-${{ matrix.target.platform }}
        build-args: >
          --target-platform ${{ matrix.target.platform }}${{ matrix.target.platform == 'linux-aarch64' && ' --no-test' || '' }}
          --channel mesomorph --channel conda-forge
    - run: |
        # https://rattler.build/latest/authentication_and_upload/#anacondaorg
        for pkg in $(find output -type f \( -name "*.conda" -o -name "*.tar.bz2" \) ); do
          echo "Uploading ${pkg}"
          rattler-build upload anaconda -v --force "${pkg}"
        done
      env:
        # tag::api-token[]
        ANACONDA_OWNER: ${{ vars.ANACONDA_OWNER }}
        ANACONDA_API_KEY: ${{ secrets.ANACONDA_API_KEY }}
        ANACONDA_CHANNEL: dev
        # ANACONDA_SERVER_URL: https://anaconda.org
        RATTLER_BUILD_LOG_STYLE: fancy
        # ANACONDA_FORCE: false
        # end::api-token[]
